# Generated by Django 5.0.2 on 2024-03-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_created_date_user_phone_user_session_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_update_own_details', 'Can update own details')]},
        ),
    ]
