# Generated by Django 5.0.2 on 2024-02-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
