# Generated by Django 5.0.2 on 2024-03-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_product_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_list',
        ),
    ]
