# Generated by Django 5.0.2 on 2024-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_product_order_product_list'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_list',
        ),
        migrations.AddField(
            model_name='order',
            name='product_list',
            field=models.ManyToManyField(null=True, to='product.product'),
        ),
    ]
